"""
base.py
-------
Base detector interface and common types.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal, Optional

from engine_blocks import Candle


@dataclass
class DetectorConfig:
    """Configuration for a detector."""
    
    enabled: bool = True
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DetectorSignal:
    """Signal generated by a detector."""
    
    detector_name: str
    pair: str
    direction: Literal["BUY", "SELL"]
    entry: float
    sl: float
    tp: float
    rr: float

    # Output kind: normal tradable signal vs informational annotation
    kind: Literal["signal", "annotation"] = "signal"
    
    # Signal strength/confidence (0.0 to 1.0)
    strength: float = 0.5
    
    # Additional metadata
    timeframe: str = ""
    reasons: List[str] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)


class BaseDetector(ABC):
    """Base class for all detectors."""
    
    name: str = "base"

    # Optional documentation metadata (safe defaults).
    doc: str = ""
    params_schema: Dict[str, Any] = {}
    examples: List[Dict[str, Any]] = []
    
    def __init__(self, config: Optional[DetectorConfig] = None):
        self.config = config or DetectorConfig()
    
    @abstractmethod
    def detect(
        self,
        pair: str,
        entry_candles: List[Candle],
        trend_candles: List[Candle],
        primitives: Any,  # PrimitiveResults
        user_config: Dict[str, Any],
    ) -> Optional[DetectorSignal]:
        """
        Detect trading signal.
        
        Args:
            pair: Trading pair symbol
            entry_candles: Entry timeframe candles
            trend_candles: Trend timeframe candles
            primitives: Pre-computed primitive results
            user_config: User-specific configuration
            
        Returns:
            DetectorSignal if signal found, None otherwise
        """
        pass
    
    def is_enabled(self) -> bool:
        """Check if detector is enabled."""
        return self.config.enabled

    def get_doc(self) -> str:
        v = getattr(self, "doc", "")
        return str(v) if v is not None else ""

    def get_params_schema(self) -> Dict[str, Any]:
        v = getattr(self, "params_schema", None)
        return dict(v) if isinstance(v, dict) else {}

    def get_examples(self) -> List[Dict[str, Any]]:
        v = getattr(self, "examples", None)
        if not isinstance(v, list):
            return []
        return [dict(x) for x in v if isinstance(x, dict)]
